issue_mapping_old_new = {
    "Data Quality"      : "Defect",
    "Performance"       : "Defect",
    "Change Request"    : "Improvement",
    "Functional defect" : "Defect",
    "UI"                : "Defect"
    }

fields_mapping_old_new = {
    "priority"          : "priority",
    "project"           : "project",
    "summary"           : "summary",
    "description"       : "description",
    "issuetype"         : "issuetype",
    "reporter"          : "reporter"
}


standard_minimum_defect = """{  'customfield_10001': %(phase)s,
                                'customfield_10022': %(Severity)s,
                                'description'      : %(description)s,
                                'environment'      : %(environment)s,
                                'issuetype'        : {'name': %(issuetype)s},
                                'project'          : {'key' : %(project)s},
                                'reporter'         : %(reporter)s,
                                'summary'          : %(summary)s
                            }"""

standard_minimum_uti = """{ 'description': %(description)s,
                            'issuetype'  : {'name': %(issuetype)s},
                            'project'    : {'key' : %(project)s},
                            'reporter'   : %(reporter)s,
                            'summary'    : %(summary)s
                          }"""


standard_minimum_epic = """{  'customfield_10014': 'Epic Name',
                               'description' : %(description)s,
                               'issuetype'   : {'name': %(issuetype)s},
                               'project'     : {'key' : %(project)s},
                               'reporter'    : %(reporter)s,,
                               'summary'     :  %(summary)s
                            }"""

new_standard_fields = {'Defect': {  'customfield_10001': 'Phase',
                                     'customfield_10022': 'Severity',
                                     'description': 'Description',
                                     'environment': 'Environment',
                                     'issuetype': 'Issue Type',
                                     'project': 'Project',
                                     'reporter': 'Reporter',
                                     'summary': 'Summary'},
                       'EPIC': {  'customfield_10014': 'Epic Name',
                                   'description': 'Description',
                                   'issuetype': 'Issue Type',
                                   'project': 'Project',
                                   'reporter': 'Reporter',
                                   'summary': 'Summary'},
                       'Improvement': {  'description': 'Description',
                                          'issuetype': 'Issue Type',
                                          'project': 'Project',
                                          'reporter': 'Reporter',
                                          'summary': 'Summary'},
                       'Sub-task': {  'description': 'Description',
                                       'issuetype': 'Issue Type',
                                       'parent': 'Parent',
                                       'project': 'Project',
                                       'reporter': 'Reporter',
                                       'summary': 'Summary'},
                       'Task': {  'description': 'Description',
                                   'issuetype': 'Issue Type',
                                   'project': 'Project',
                                   'reporter': 'Reporter',
                                   'summary': 'Summary'},
                       'User Story': {  'description': 'Description',
                                         'issuetype': 'Issue Type',
                                         'project': 'Project',
                                         'reporter': 'Reporter',
                                         'summary': 'Summary'}}


old_project_all_fields_all_issues = {  'Change Request': {   'Affects Version/s': 'versions',
                                                             'Assignee': 'assignee',
                                                             'Attachment': 'attachment',
                                                             'Comment': 'customfield_10628',
                                                             'Component/s': 'components',
                                                             'Description': 'description',
                                                             'Due Date': 'duedate',
                                                             'Epic Link': 'customfield_10811',
                                                             'Estimated Effort': 'customfield_13411',
                                                             'Expected Result': 'customfield_11433',
                                                             'Fix Version/s': 'fixVersions',
                                                             'Issue Type': 'issuetype',
                                                             'Labels': 'labels',
                                                             'Priority': 'priority',
                                                             'Project': 'project',
                                                             'Reporter': 'reporter',
                                                             'Severity': 'customfield_10627',
                                                             'Sprint': 'customfield_10810',
                                                             'Steps to Reproduce': 'customfield_11015',
                                                             'Summary': 'summary',
                                                             'Vendor Tracking ID': 'customfield_12016'},
                                       'Data Quality': {  'Affects Version/s': 'versions',
                                                           'Assignee': 'assignee',
                                                           'Attachment': 'attachment',
                                                           'Comment': 'customfield_10628',
                                                           'Component/s': 'components',
                                                           'Description': 'description',
                                                           'Due Date': 'duedate',
                                                           'Epic Link': 'customfield_10811',
                                                           'Estimated Effort': 'customfield_13411',
                                                           'Expected Result': 'customfield_11433',
                                                           'Fix Version/s': 'fixVersions',
                                                           'Issue Type': 'issuetype',
                                                           'Labels': 'labels',
                                                           'Priority': 'priority',
                                                           'Project': 'project',
                                                           'Reporter': 'reporter',
                                                           'Severity': 'customfield_10627',
                                                           'Sprint': 'customfield_10810',
                                                           'Steps to Reproduce': 'customfield_11015',
                                                           'Summary': 'summary',
                                                           'Vendor Tracking ID': 'customfield_12016'},
                                       'Functional defect': {  'Affects Version/s': 'versions',
                                                                'Assignee': 'assignee',
                                                                'Attachment': 'attachment',
                                                                'Comment': 'customfield_10628',
                                                                'Component/s': 'components',
                                                                'Description': 'description',
                                                                'Due Date': 'duedate',
                                                                'Epic Link': 'customfield_10811',
                                                                'Estimated Effort': 'customfield_13411',
                                                                'Expected Result': 'customfield_11433',
                                                                'Fix Version/s': 'fixVersions',
                                                                'Issue Type': 'issuetype',
                                                                'Labels': 'labels',
                                                                'Priority': 'priority',
                                                                'Project': 'project',
                                                                'Reporter': 'reporter',
                                                                'Severity': 'customfield_10627',
                                                                'Sprint': 'customfield_10810',
                                                                'Steps to Reproduce': 'customfield_11015',
                                                                'Summary': 'summary',
                                                                'Vendor Tracking ID': 'customfield_12016'},
                                           'Performance': {  'Affects Version/s': 'versions',
                                                              'Assignee': 'assignee',
                                                              'Attachment': 'attachment',
                                                              'Comment': 'customfield_10628',
                                                              'Component/s': 'components',
                                                              'Description': 'description',
                                                              'Due Date': 'duedate',
                                                              'Epic Link': 'customfield_10811',
                                                              'Estimated Effort': 'customfield_13411',
                                                              'Expected Result': 'customfield_11433',
                                                              'Fix Version/s': 'fixVersions',
                                                              'Issue Type': 'issuetype',
                                                              'Labels': 'labels',
                                                              'Priority': 'priority',
                                                              'Project': 'project',
                                                              'Reporter': 'reporter',
                                                              'Severity': 'customfield_10627',
                                                              'Sprint': 'customfield_10810',
                                                              'Steps to Reproduce': 'customfield_11015',
                                                              'Summary': 'summary',
                                                              'Vendor Tracking ID': 'customfield_12016'},
                                           'UI': {  'Affects Version/s': 'versions',
                                                     'Assignee': 'assignee',
                                                     'Attachment': 'attachment',
                                                     'Comment': 'customfield_10628',
                                                     'Component/s': 'components',
                                                     'Description': 'description',
                                                     'Due Date': 'duedate',
                                                     'Epic Link': 'customfield_10811',
                                                     'Estimated Effort': 'customfield_13411',
                                                     'Expected Result': 'customfield_11433',
                                                     'Fix Version/s': 'fixVersions',
                                                     'Issue Type': 'issuetype',
                                                     'Labels': 'labels',
                                                     'Priority': 'priority',
                                                     'Project': 'project',
                                                     'Reporter': 'reporter',
                                                     'Severity': 'customfield_10627',
                                                     'Sprint': 'customfield_10810',
                                                     'Steps to Reproduce': 'customfield_11015',
                                                     'Summary': 'summary',
                                                     'Vendor Tracking ID': 'customfield_12016'}}

# this fields are used to filter the fields that are needed to be mapped
needed_fields = ['Summary', 'Description', 'Reporter', 'Project', 'Environment', 'Description', 'Severity']

# this containds the needed relations
needed_relation = ['issuelink', 'attachment', 'parent']